### ISSUE TITLE
Support health checks and HTTPS certifications for ELB

### ISSUE THREAD

**Issue by s4mur4i** [puppetlabs/puppetlabs-aws#145] opened 2015-04-08 15:58 UTC
We have some elb-s that we would like to manage with puppet. They have client facing port of 443 for https. On amazon console we need to upload the certificates, and chains for it to function.
In module I see no option to do it.
Also to configure the healthchecks for an ELB is also missing. For example to make it ping port 80 /index.html in the background.

Thanks
Krisztian

**Comment by garethr** [comment] 2015-04-09 07:58
@s4mur4i thanks for mentioning this, we have somewhat minimal support at the moment but we're definitely interested in expanding that. If you'll like to try and add this functionality I'd be happy to help, no problem if not. I'll update this issue when we do get to working on adding support for these parts of ELB.

**Comment by s4mur4i** [comment] 2015-04-09 08:13
@garethr I would give it a go to implementing it, Can you direct me which files to investigate?
I also read the contribution page, I might also need some help with the testing part.
Thanks

**Comment by garethr** [comment] 2015-04-09 08:17
The main files you're interested in are the type:  https://github.com/puppetlabs/puppetlabs-aws/blob/master/lib/puppet/type/elb_loadbalancer.rb and the provider: https://github.com/puppetlabs/puppetlabs-aws/blob/master/lib/puppet/provider/elb_loadbalancer/v2.rb

The type mainly describes what the DSL looks like, so what properties you can set in Puppet when describing an ELB.

The provider does the work and makes the various API calls. The AWS SDK docs are at http://docs.aws.amazon.com/sdkforruby/api/index.html.

Do ask any questions here, I'm happy to help you get started.

**Comment by daveseff** [comment] 2015-09-16 20:42
@garethr and @s4mur4i , I have created PR #215 to address the SSL certificate. I'm currently working on the ability to configure the healthcleck similar to adding of the instances in another branch:

    def self.configure_healthcheck(region, load_balancer_name)
      elb_client(region).configure_health_check(
      load_balancer_name: load_balancer_name,
      health_check: {
        target: "HTTP:80/probe.php",
        interval: 30,
        timeout: 20,
        unhealthy_threshold: 4,
        healthy_threshold: 5,
      },
    )
    end

Of course this needs to be parameterized and not hardcoded in this fashion. so stay tuned.

**Comment by mikronac** [comment] 2015-11-25 18:08
@daveseff any progress? :)

**Comment by daveseff** [comment] 2016-02-05 03:31
@mikronac Yes. I had created #215 which included changes to the README.md describing how to implement. I'm not sure why it's not getting merged in other than other people decided to submit similar  PRs.

**Comment by ahenroid** [comment] 2017-03-03 21:46
@s4mur4i @dusansusic  @daveseff, I believe this was resolved by #215. Can I close this issue?

**Comment by zleswomp** [comment] 2017-03-03 21:50
I can confirm this works, as we are using SSL and health checks, and managing them both under puppet.  Certificate contents are uploaded manually, and the ID is specified in puppet.

**Closed by zleswomp** 2017-03-03 21:50 UTC
Labels: enhancement
